name: fly

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        type: string
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency: deploy-group

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # v1.5

      - name: Deploy to Fly.io
        run: |
          tag="${{ inputs.commit_sha }}"
          if [[ "$tag" = "" ]]; then
            # Fall back to whatever is checked out as default
            tag="${{ github.sha }}"
          fi
          flyctl deploy -i "ghcr.io/${{ github.repository }}:$tag"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
